name: stapes_home
description: "AI Home Automation App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0-282.3.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus:
  dotted_border:
  http:
  dartz:
  pull_to_refresh:
  shared_preferences: 
  hive_flutter:
  path_provider:
  hive: 
  mobile_scanner: 
  lottie:
  flutter_lints:
  pinput:
  connectivity_plus:
  wifi_scan:
  network_info_plus:
  permission_handler:
  flutter_svg:
  camera:
  provider:
  uuid:
  internet_connection_checker:
  equatable:
  logger:
  get_it:
  flutter_bloc:
  go_router:
  intl:
  flutter_keyboard_visibility:
  freezed_annotation:
  bloc:
  sqflite:
  path:
  device_preview:
  device_user_agent:
  firebase_core:
  firebase_messaging:
  device_info_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator:
  flutter_launcher_icons:
  freezed:

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/loties/
    - assets/icons/sso/
    - assets/icons/home/
    - assets/icons/nodes/
    - assets/icons/devices/
    - assets/icons/navbar/

  # fonts:

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true
  remove_alpha_ios: true
  # adaptive_icon_background: "#161616"
  # adaptive_icon_foreground: "assets/logo.png"
  # adaptive_icon_padding: true

flutter_lints:
  include: package:flutter_lints/recommended.yaml
