name: stapes_home
description: "AI Home Automation App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0-282.3.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.12
  dotted_border: ^2.1.0
  http: ^1.2.1
  dartz:
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  hive: ^2.2.3
  mobile_scanner: ^5.2.3
  lottie: ^3.1.2
  flutter_lints: ^4.0.0
  pinput: ^5.0.0
  connectivity_plus: ^6.0.5
  wifi_iot: ^0.3.19+1
  wifi_scan: ^0.4.1+1
  network_info_plus: ^6.0.1
  permission_handler: ^11.3.1
  flutter_svg: any
  camera: ^0.11.0+2
  provider: ^6.1.2
  uuid: ^4.5.0
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
  logger:
  get_it:
  flutter_bloc:
  go_router: ^14.4.1
  intl:
  flutter_keyboard_visibility:
  freezed_annotation:
  bloc: ^8.1.4
  sqflite: ^2.4.1
  path: ^1.9.0
  device_preview:
  device_user_agent:
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  freezed:

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/loties/
    - assets/icons/sso/
    - assets/icons/home/
    - assets/icons/nodes/
    - assets/icons/devices/
    - assets/icons/navbar/

  # fonts:

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true
  remove_alpha_ios: true
  # adaptive_icon_background: "#161616"
  # adaptive_icon_foreground: "assets/logo.png"
  # adaptive_icon_padding: true

flutter_lints:
  include: package:flutter_lints/recommended.yaml
