name: jarvis
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0-282.3.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.32.7
  qr_code_scanner: ^1.0.0
  image_picker: ^0.8.4+4
  image_cropper: ^1.5.0
  http: ^1.2.1
  shared_preferences: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
