// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKjot0Pjmjbpa934KUFjU3NbpMo24ITl4',
    appId: '1:977103763608:android:6610e2a9f120268e9878ed',
    messagingSenderId: '977103763608',
    projectId: 'stapeshome-d113d',
    // Here initialization of storageBucket does not mean that it is being used.
    // This file is autogenerated.
    storageBucket: 'stapeshome-d113d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClxslWZN_B0YFgdUMS6bWsgPLH2BtfYys',
    appId: '1:977103763608:ios:6ef969dcaf39907d9878ed',
    messagingSenderId: '977103763608',
    projectId: 'stapeshome-d113d',
    iosBundleId: 'com.stapesai.home',
    // Here initialization of storageBucket does not mean that it is being used.
    // This file is autogenerated.
    storageBucket: 'stapeshome-d113d.firebasestorage.app',
  );
}
